mv src/fdnpkg16.c src2/
mv src/crc32.c src2/
mv src/inf.c src2/
mv src/kprintf.c src2/
mv src/kprintf0.c src2/
mv src/kitten.c src2/
mv src/fileexst.c src2/
mv src/http.c src2/
mv src/libgz.c src2/
mv src/libunzip.c src2/
mv src/loadconf.c src2/
mv src/lsm.c src2/
mv src/net.c src2/
mv src/lzmadec.c src2/
mv src/pkgdb.c src2/
mv src/pkginst.c src2/
mv src/pkgsrch.c src2/
mv src/pkgrem.c src2/
mv src/readenv.c src2/
mv src/showinst.c src2/
mv src/getdelim.c src2/
mv src/rtrim.c src2/
mv src/parsecmd.c src2/
mv src/parseurl.c src2/
mv src/helpers.c src2/

mv src/fdnpkg16.h src2/
mv src/crc32.h src2/
mv src/inf.h src2/
mv src/kprintf.h src2/
mv src/kprintf0.h src2/
mv src/kitten.h src2/
mv src/fileexst.h src2/
mv src/http.h src2/
mv src/libgz.h src2/
mv src/libunzip.h src2/
mv src/loadconf.h src2/
mv src/lsm.h src2/
mv src/net.h src2/
mv src/lzmadec.h src2/
mv src/pkgdb.h src2/
mv src/pkginst.h src2/
mv src/pkgsrch.h src2/
mv src/pkgrem.h src2/
mv src/readenv.h src2/
mv src/showinst.h src2/
mv src/getdelim.h src2/
mv src/rtrim.h src2/
mv src/parsecmd.h src2/
mv src/parseurl.h src2/
mv src/helpers.h src2/
